"""Stable SoulOS Problem Details ``code`` values (RFC 7807 extension)."""

TURN_CONTRACT_VIOLATION = "TURN_CONTRACT_VIOLATION"
TURN_REJECT_TOKEN = "TURN_REJECT_TOKEN"
TURN_STEP_MISMATCH = "TURN_STEP_MISMATCH"
TURN_STATE_STALE = "TURN_STATE_STALE"
TURN_SESSION_EXPIRED = "TURN_SESSION_EXPIRED"

TURN_ERROR_CODES = (
    TURN_CONTRACT_VIOLATION,
    TURN_REJECT_TOKEN,
    TURN_STEP_MISMATCH,
    TURN_STATE_STALE,
    TURN_SESSION_EXPIRED,
)
