#!/usr/bin/env python3
"""Generate docs/dependency-licenses.generated.md from installed Python + npm deps."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "dependency-licenses.generated.md"

# Packages we never treat as third-party in the inventory
OWN_PREFIXES = ("soulos", "@soulos/")


def _run(cmd: list[str], *, cwd: Path | None = None) -> str:
    proc = subprocess.run(
        cmd,
        cwd=cwd or ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stderr}"
        )
    return proc.stdout


def python_rows(python: str) -> list[tuple[str, str, str]]:
    script = (
        "import json,importlib.metadata as m;"
        "print(json.dumps(["
        "{'name':d.metadata['Name'],'version':d.version,"
        "'license':(d.metadata.get('License') or d.metadata.get('License-Expression') or 'UNKNOWN')}"
        " for d in m.distributions()]))"
    )
    raw = _run([python, "-c", script])
    data = json.loads(raw)
    rows: list[tuple[str, str, str]] = []
    for item in data:
        name = str(item.get("name") or "")
        if not name or name.lower().startswith(OWN_PREFIXES):
            continue
        rows.append((name, str(item.get("version") or ""), str(item.get("license") or "UNKNOWN")))
    rows.sort(key=lambda r: (r[0].lower(), r[1]))
    # de-dupe by name keeping first
    seen: set[str] = set()
    unique: list[tuple[str, str, str]] = []
    for row in rows:
        key = row[0].lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(row)
    return unique


def npm_rows() -> list[tuple[str, str, str]]:
    nm = ROOT / "node_modules"
    if not nm.is_dir():
        return []
    rows: list[tuple[str, str, str]] = []
    for pkg in nm.rglob("package.json"):
        # Skip nested package.json inside package internals we don't care about
        parts = pkg.relative_to(nm).parts
        if "node_modules" in parts[1:]:
            continue
        try:
            data = json.loads(pkg.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        name = str(data.get("name") or "")
        if not name or name.startswith(OWN_PREFIXES) or name == "soulos-monorepo":
            continue
        lic = data.get("license") or data.get("licenses") or "UNKNOWN"
        if isinstance(lic, dict):
            lic = lic.get("type") or lic.get("name") or "UNKNOWN"
        if isinstance(lic, list):
            lic = ", ".join(
                str(x.get("type") if isinstance(x, dict) else x) for x in lic
            )
        rows.append((name, str(data.get("version") or ""), str(lic)))
    rows.sort(key=lambda r: (r[0].lower(), r[1]))
    seen: set[str] = set()
    unique: list[tuple[str, str, str]] = []
    for row in rows:
        key = row[0].lower()
        if key in seen:
            continue
        seen.add(key)
        unique.append(row)
    return unique


def render(py_rows: list[tuple[str, str, str]], js_rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "<!-- Generated by scripts/generate-dependency-licenses.py — do not edit by hand. -->",
        "",
        "# Dependency license inventory",
        "",
        "Generated snapshot of **installed** third-party packages for SoulOS packages",
        "(kernel, gateway, studio, inference-bridge, Python SDK) and the npm workspace.",
        "SoulOS first-party packages are MIT — see [LICENSE](../LICENSE).",
        "",
        "Regenerate:",
        "",
        "```bash",
        "python3 scripts/generate-dependency-licenses.py",
        "```",
        "",
        "## Python (site-packages of the active interpreter)",
        "",
        "| Package | Version | License |",
        "|---------|---------|---------|",
    ]
    if not py_rows:
        lines.append("| _(none found)_ | | |")
    else:
        for name, ver, lic in py_rows:
            safe = lic.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{name}` | {ver} | {safe} |")

    lines.extend(
        [
            "",
            "## npm (workspace `node_modules`)",
            "",
            "| Package | Version | License |",
            "|---------|---------|---------|",
        ]
    )
    if not js_rows:
        lines.append("| _(run `npm ci` then regenerate)_ | | |")
    else:
        for name, ver, lic in js_rows:
            safe = lic.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{name}` | {ver} | {safe} |")

    lines.extend(
        [
            "",
            "## Policy notes",
            "",
            "- Prefer **MIT / BSD / Apache-2.0 / ISC / PSF** dependencies.",
            "- **MPL-2.0** (e.g. `certifi`) is weak file-level copyleft — keep unmodified.",
            "- Block **GPL / AGPL / SSPL / BUSL** and Commons Clause unless counsel reviews.",
            "- Web fonts loaded from Google Fonts (Figtree, Fraunces) are **OFL-1.1**;",
            "  if font files are ever vendored into this repo, ship the OFL license text",
            "  beside them (see [THIRD_PARTY_NOTICES.md](../THIRD_PARTY_NOTICES.md)).",
            "",
        ]
    )
    return "\n".join(lines)


FORBIDDEN = (
    "GPL",
    "AGPL",
    "SSPL",
    "BUSL",
    "COMMONS CLAUSE",
    "CC-BY-NC",
)


def _license_forbidden(license_text: str) -> bool:
    upper = license_text.upper()
    # Allow LGPL mention only if not standalone strong copyleft — still flag LGPL for review
    for needle in FORBIDDEN:
        if needle in upper:
            # "Apache-2.0 OR GPL-2.0" still contains GPL — flag it
            return True
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated content differs from the committed file",
    )
    parser.add_argument(
        "--fail-on-copyleft",
        action="store_true",
        help="Fail if any inventoried package declares GPL/AGPL/SSPL/BUSL/etc.",
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python interpreter whose site-packages to inventory",
    )
    args = parser.parse_args(argv)

    py_rows = python_rows(args.python)
    js_rows = npm_rows()
    content = render(py_rows, js_rows)

    if args.fail_on_copyleft:
        bad = [
            (ecosystem, name, ver, lic)
            for ecosystem, rows in (("Python", py_rows), ("npm", js_rows))
            for name, ver, lic in rows
            if _license_forbidden(lic)
        ]
        if bad:
            print("Forbidden or high-risk licenses detected:", file=sys.stderr)
            for ecosystem, name, ver, lic in bad:
                print(f"  [{ecosystem}] {name}@{ver}: {lic}", file=sys.stderr)
            return 1

    if args.check:
        if not OUT.is_file():
            print(f"missing {OUT}; run without --check to generate", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != content:
            print(
                f"{OUT} is out of date. Run:\n"
                f"  {args.python} scripts/generate-dependency-licenses.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUT} matches installed inventory")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT} ({len(py_rows)} Python, {len(js_rows)} npm packages)")
    if shutil.which("pip-licenses"):
        print("(pip-licenses is available; inventory uses importlib.metadata)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
